### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Coolzhou** [burning-git/BRMultilevelMeun#1]
我的问题是怎么设置,当滚动右边tableView，左边菜单对应滚动到，当前菜单。如：右边tableview 滚动到菜单2那组section ,左边菜单也变成菜单2为选择状态； 右边tableview 滚动到菜单5那组section ,左边菜单也变成菜单5为选择状态。我想不出来解决方法，求指导一下

**Comment by burning-git** [comment]
你是 需要 初始化的 时候，滚动到指定 位置吗？？？ 目前是默认 第一个

**Comment by Coolzhou** [comment]
不是，因为右边的tableview的每个section,是对应左边的tableview的row。 所以我想监听到右边tableview是滚动到哪一组section ，左边tableview动态的也跟着指定到对应的row.这个有方法吗？主要是监听右边tableview是滚动到哪一组section，我不知道有什么方法。（现在Demo是滚动右边tableView，左边指定是不改变的）

**Comment by burning-git** [comment]
目前 是用的tablew 和 collectionView 做的 。左边tablew 点击时，，是刷新 右边的collection 数据源
