### ISSUE TITLE
添加navvontroller就变样了

### ISSUE THREAD

**Issue by beiguancyc** [burning-git/BRMultilevelMeun#2]

**Comment by burning-git** [comment]
修复了。。你更新版本.谢谢反馈

**Comment by beiguancyc** [comment]
如果左边的数据库条目少，选中除第一个外的条目时，第一个条目背景色还是白色，界面会有两个条目被选中，我尝试修改代码没搞定。。。

**Comment by beiguancyc** [comment]
![Uploading iOS Simulator Screen Shot 2015年8月27日 
![ios simulator screen shot 2015 8 27 11 59 00](https://cloud.githubusercontent.com/assets/12932389/9512548/545a1dcc-4cb6-11e5-811e-422b1f47c06c.png)
上午11.59.00.png…]()

**Comment by burning-git** [comment]
这个 字符串长度，大概 4、5个，多了目前不支持多行

**Comment by beiguancyc** [comment]
我不是说多行，而是第一行和第三行背景色都是选中色

**Comment by burning-git** [comment]
这个 你 用的最新版本吗

**Comment by beiguancyc** [comment]
我用刚下载下来的你的代码示例
![ios simulator screen shot 2015 9 5 9 01 54](https://cloud.githubusercontent.com/assets/12932389/9699330/7f4bbc5e-5411-11e5-9d2d-7ebf6266e733.png)

**Comment by burning-git** [comment]
出现这个 情况的 操作是怎么样的呢？

**Comment by beiguancyc** [comment]
你的示例里，把左边菜单项改成6个即可重现。

**Comment by burning-git** [comment]
我这边没有重现呢，，你看看你的 左边只有 5个呢？

**Comment by beiguancyc** [comment]
只要少于需要滚动的行数就有，随便点击除第0行以外的行就有了。

**Comment by burning-git** [comment]
嗯，问题重现，我去修改下。。。

**Comment by burning-git** [comment]
问题修复了，你更新下版本呢

**Comment by beiguancyc** [comment]
现在打开啥都没有了。。。。

**Comment by burning-git** [comment]
修复了，修改错东西了

**Comment by beiguancyc** [comment]
我修改后，
NSInteger countMax=6;
view.needToScorllerIndex=0;
依然多选。

**Comment by burning-git** [comment]
你再试试，修复了，needToScorllerIndex 里面 取消判断，之前是>0 。等于0 的情况没有包含进去。。

**Comment by beiguancyc** [comment]
已验证。兄台太敬业了，我都不好意思了

**Comment by burning-git** [comment]
没事，共同学习！
