### ISSUE TITLE
关于滑动右侧collectionview时head的标题会消失

### ISSUE THREAD

**Issue by OrageKK** [burning-git/BRMultilevelMeun#6]
求指教一下是怎么回事，我是用代码写的，
`- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath{
    
    UICollectionReusableView *reusableview = nil;
    
    if (kind == UICollectionElementKindSectionHeader){
        
        UICollectionReusableView *headView =  [collectionView dequeueReusableSupplementaryViewOfKind :kind   withReuseIdentifier:kMultilevelCollectionHeader forIndexPath:indexPath];
        
        
        NSString *str = _dataArray[indexPath.section];
        self.label.text= str;
        
        headView.backgroundColor = [UIColor hm_colorWithHex:0xE0E0E0];
        reusableview = headView;
        if (indexPath.section == 0) {
            
        }else {
            
            if (![reusableview.subviews containsObject:self.label]) {
                [reusableview addSubview:self.label];
            }
        }
    }else {
        UICollectionReusableView *footView =  [collectionView dequeueReusableSupplementaryViewOfKind :kind   withReuseIdentifier:@"FooterView" forIndexPath:indexPath];
        reusableview = footView;
    }
    return reusableview;
    
}`

**Comment by burning-git** [comment]
你这个UICollectionReusableView 弄错了，，，比如 你有 10个header。应该是 10个 label。目前你只是设置了一个 label....(self.label)
